In [37]:
#Treinando numpy e pandas
## Criando base de dados

In [38]:
##importando bibiliotecas
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

In [39]:
##teste
print ("teste de print")

teste de print

In [40]:
#criando base de Ordens de Serviço
# -------------------------
# Parâmetros
# -------------------------
N = 1000
np.random.seed(42)
# -------------------------
# Dados básicos
# -------------------------
OrderID = np.arange(1, N+1)
EquipmentID = [f"COLH-{str(i).zfill(3)}" for i in np.random.randint(1, 50, N)]
EquipmentType = ["Colhedora"] * N
OrderType = np.random.choice(["Corretiva", "Preventiva"], N, p=[0.65, 0.35])

Priority = np.random.randint(1, 6, N)

In [41]:
# Datas
start_date = datetime(2024, 1, 1)
CreationDate = [start_date + timedelta(days=int(np.random.randint(0, 365))) for _ in range(N)]
FinishDate = [date + timedelta(days=int(np.random.randint(1, 30))) for date in CreationDate]

In [42]:
# Status
Status = np.random.choice(["Aberta", "Em execução", "Concluída"], N, p=[0.10, 0.20, 0.70])

In [43]:
# Horas de parada (maiores para corretivas)
DowntimeHours = [
    round(abs(np.random.normal(8, 3)) if t == "Corretiva" else abs(np.random.normal(3, 1)), 2)
    for t in OrderType
]

In [44]:
# Custos
EstimatedCost = np.round(np.random.normal(5000, 1500, N), 2)
ActualCost = EstimatedCost + np.round(np.random.normal(300, 800, N), 2)

In [45]:
# Equipes
MaintenanceGroup = np.random.choice(["Mecânica", "Elétrica", "Hidráulica"], N)

In [46]:
# Descrição
Description = [
    "Manutenção programada" if t == "Preventiva" else "Falha inesperada"
    for t in OrderType
]

In [47]:
# Se a OS está aberta → Data_Fechamento fica vazia
df.loc[df["Status"] == "Aberta", "Data_Fechamento"] = pd.NaT

In [48]:
# Idade da OS
AgeDays = [(f - c).days for c, f in zip(CreationDate, FinishDate)]

In [49]:
# STATUS DA ORDEM DE SERVIÇO
# ------------------------

# 30% abertas, 70% fechadas
df["Status"] = np.random.choice(
    ["Aberta", "Fechada"],
    size=len(df),
    p=[0.30, 0.70]
)

In [56]:
# -------------------------
# Montagem do DataFrame
# -------------------------

df = pd.DataFrame({
    "OrderID": OrderID,
    "EquipmentID": EquipmentID,
    "EquipmentType": EquipmentType,
    "OrderType": OrderType,
    "Priority": Priority,
    "CreationDate": CreationDate,
    "FinishDate": FinishDate,
    "Status": Status,
    "DowntimeHours": DowntimeHours,
    "EstimatedCost": EstimatedCost,
    "ActualCost": ActualCost,
    "MaintenanceGroup": MaintenanceGroup,
    "Description": Description,
    "AgeDays": AgeDays,
    "Status": Status
})

df.head(20)

,OrderID,EquipmentID,EquipmentType,OrderType,Priority,CreationDate,FinishDate,Status,DowntimeHours,EstimatedCost,ActualCost,MaintenanceGroup,Description,AgeDays
0,1,COLH-039,Colhedora,Preventiva,4,2024-09-29,2024-10-03,Concluída,4.11,6697.72,6592.89,Hidráulica,Manutenção programada,4
1,2,COLH-029,Colhedora,Preventiva,1,2024-04-08,2024-04-26,Concluída,1.05,5172.28,4717.86,Mecânica,Manutenção programada,18
2,3,COLH-015,Colhedora,Preventiva,5,2024-09-08,2024-10-06,Concluída,4.13,5737.81,7021.30,Hidráulica,Manutenção programada,28
3,4,COLH-043,Colhedora,Corretiva,3,2024-12-03,2024-12-14,Concluída,7.80,3035.55,3159.11,Mecânica,Falha inesperada,11
4,5,COLH-008,Colhedora,Preventiva,2,2024-04-13,2024-04-18,Concluída,3.13,5348.32,5799.93,Hidráulica,Manutenção programada,5
5,6,COLH-021,Colhedora,Corretiva,3,2024-08-01,2024-08-16,Em execução,5.16,3986.62,4793.57,Mecânica,Falha inesperada,15
6,7,COLH-039,Colhedora,Preventiva,2,2024-09-05,2024-10-03,Em execução,1.19,5711.95,4848.12,Mecânica,Manutenção programada,28
7,8,COLH-019,Colhedora,Corretiva,3,2024-05-31,2024-06-18,Em execução,8.32,7200.74,7003.66,Mecânica,Falha inesperada,18
8,9,COLH-023,Colhedora,Preventiva,2,2024-09-06,2024-09-08,Concluída,3.55,5434.28,6532.09,Elétrica,Manutenção programada,2
9,10,COLH-011,Colhedora,Preventiva,4,2024-10-01,2024-10-23,Em execução,3.70,3648.72,3510.25,Hidráulica,Manutenção programada,22
10,11,COLH-011,Colhedora,Preventiva,2,2024-06-13,2024-06-24,Concluída,3.59,5939.70,4868.79,Mecânica,Manutenção programada,11
11,12,COLH-024,Colhedora,Corretiva,2,2024-12-06,2025-01-01,Concluída,9.10,5602.68,5180.87,Elétrica,Falha inesperada,26
12,13,COLH-036,Colhedora,Corretiva,1,2024-01-08,2024-02-02,Concluída,5.23,8087.90,8158.89,Mecânica,Falha inesperada,25
13,14,COLH-040,Colhedora,Preventiva,2,2024-10-10,2024-10-23,Em execução,3.77,5380.95,5814.36,Elétrica,Manutenção programada,13
14,15,COLH-024,Colhedora,Corretiva,1,2024-01-05,2024-01-09,Aberta,4.89,4121.79,4365.14,Mecânica,Falha inesperada,4
15,16,COLH-003,Colhedora,Preventiva,5,2024-05-24,2024-06-15,Aberta,4.11,6155.96,5964.59,Mecânica,Manutenção programada,22
16,17,COLH-022,Colhedora,Preventiva,1,2024-04-10,2024-04-17,Concluída,2.92,4808.48,5859.93,Elétrica,Manutenção programada,7
17,18,COLH-002,Colhedora,Corretiva,4,2024-06-12,2024-07-11,Concluída,7.85,5120.38,5317.13,Elétrica,Falha inesperada,29
18,19,COLH-024,Colhedora,Preventiva,1,2024-05-26,2024-06-06,Em execução,3.87,3607.29,4074.81,Hidráulica,Manutenção programada,11
19,20,COLH-044,Colhedora,Corretiva,5,2024-03-04,2024-03-26,Em execução,11.00,4816.35,4667.59,Hidráulica,Falha inesperada,22

In [51]:
#Idade media das OS's
df["AgeDays"].mean()

np.float64(15.61)

In [52]:
#Idade média por tipo de Ordem
df.groupby("OrderType")["AgeDays"].mean()

OrderType
Corretiva     15.715596
Preventiva    15.410405
Name: AgeDays, dtype: float64

In [53]:
##Idade média por equipamento
df.groupby("EquipmentID")["AgeDays"].mean().sort_values(ascending=False)

EquipmentID
COLH-012    18.619048
COLH-004    18.588235
COLH-001    18.458333
COLH-032    18.400000
COLH-040    17.882353
COLH-044    17.857143
COLH-046    17.461538
COLH-007    17.428571
COLH-021    17.421053
COLH-006    17.263158
COLH-003    17.217391
COLH-002    17.047619
COLH-043    17.000000
COLH-011    17.000000
COLH-035    16.928571
COLH-049    16.851852
COLH-015    16.812500
COLH-016    16.619048
COLH-009    16.611111
COLH-048    16.545455
COLH-036    16.380952
COLH-020    16.333333
COLH-031    16.200000
COLH-037    15.920000
COLH-042    15.529412
COLH-024    15.500000
COLH-028    15.482759
COLH-008    15.409091
COLH-030    15.250000
COLH-029    15.210526
COLH-010    15.187500
COLH-045    15.083333
COLH-041    14.888889
COLH-038    14.785714
COLH-027    14.437500
COLH-026    14.333333
COLH-034    14.111111
COLH-019    14.052632
COLH-014    13.888889
COLH-018    13.875000
COLH-033    13.821429
COLH-022    13.681818
COLH-017    13.636364
COLH-013    13.470588
COLH-039    13.080000
COLH-005    12.956522
COLH-025    12.750000
COLH-047    12.692308
COLH-023    12.652174
Name: AgeDays, dtype: float64

In [58]:
#exibir os em aberto
df_abertas = df[df["Status"] == "Em execução"]
df_abertas.head()

,OrderID,EquipmentID,EquipmentType,OrderType,Priority,CreationDate,FinishDate,Status,DowntimeHours,EstimatedCost,ActualCost,MaintenanceGroup,Description,AgeDays
5,6,COLH-021,Colhedora,Corretiva,3,2024-08-01,2024-08-16,Em execução,5.16,3986.62,4793.57,Mecânica,Falha inesperada,15
6,7,COLH-039,Colhedora,Preventiva,2,2024-09-05,2024-10-03,Em execução,1.19,5711.95,4848.12,Mecânica,Manutenção programada,28
7,8,COLH-019,Colhedora,Corretiva,3,2024-05-31,2024-06-18,Em execução,8.32,7200.74,7003.66,Mecânica,Falha inesperada,18
9,10,COLH-011,Colhedora,Preventiva,4,2024-10-01,2024-10-23,Em execução,3.70,3648.72,3510.25,Hidráulica,Manutenção programada,22
13,14,COLH-040,Colhedora,Preventiva,2,2024-10-10,2024-10-23,Em execução,3.77,5380.95,5814.36,Elétrica,Manutenção programada,13

In [61]:
df_abertas_criticas = df[
    (df["Status"] == "Aberta") &
    (df["OrderType"] == "Corretiva")
]

df_abertas_criticas.head()

,OrderID,EquipmentID,EquipmentType,OrderType,Priority,CreationDate,FinishDate,Status,DowntimeHours,EstimatedCost,ActualCost,MaintenanceGroup,Description,AgeDays
14,15,COLH-024,Colhedora,Corretiva,1,2024-01-05,2024-01-09,Aberta,4.89,4121.79,4365.14,Mecânica,Falha inesperada,4
66,67,COLH-004,Colhedora,Corretiva,1,2024-11-24,2024-12-19,Aberta,5.62,3203.78,2755.84,Elétrica,Falha inesperada,25
68,69,COLH-018,Colhedora,Corretiva,4,2024-04-25,2024-05-18,Aberta,7.03,3750.17,5273.76,Mecânica,Falha inesperada,23
84,85,COLH-045,Colhedora,Corretiva,5,2024-01-22,2024-01-31,Aberta,5.62,3548.24,3886.68,Mecânica,Falha inesperada,9
89,90,COLH-025,Colhedora,Corretiva,5,2024-02-23,2024-03-01,Aberta,6.34,3712.98,4156.54,Hidráulica,Falha inesperada,7

In [65]:
#importando dados para CSV
df.to_csv("ordens_servico.csv", index=False, encoding="utf-8")